services:
  postgres-db:
    image: postgres:15-alpine
    container_name: smartbus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: smartbus_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smartbus_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: smartbus-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://admin:secretpassword@postgres-db:5432/smartbus_db
      JWT_SECRET: change-me-in-prod
      JWT_EXPIRES_IN: 1h
      JWT_COOKIE_EXPIRES_IN: 7
      CLIENT_URL: http://localhost:8080
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./Frontend/UI
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    container_name: smartbus-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  pgdata: # This ensures your DB data isn't deleted if the container stops